# docker-compose up --build

version: "3.8"

services:
  db:
    image: postgres:15
    container_name: jiofamily-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
  app:
    build: .
    container_name: jiofamily-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  db_data:
