debug: false

server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    generate-unique-name: false
    # name: content
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always
  #     schema-locations: always
  # level:
  #   org:
  #     springfremwork:
  #       jdbc: DEBUG
  # h2:
  #   console:
  #     enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
